# 01 - Data Understanding

## Objective

The objective of this step is to understand the structure, quality, and business meaning of the Global Superstore dataset before performing any analysis.

At this stage, the goal is not to draw conclusions yet, but to verify whether the dataset is reliable and suitable for business analysis.

In [44]:
import pandas as pd
import numpy as np
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:,.2f}".format)

## 1. First Look at the Data

The first step is to inspect the dataset visually in order to understand its structure, columns, and general format.

In [45]:
df = pd.read_csv("../data/raw/superstore.csv")

print("First 5 rows:")
display(df.head())

print("Last 5 rows:")
display(df.tail())

print("Random sample:")
display(df.sample(5, random_state=42))

First 5 rows:

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.00,US,1,2011-01-07 00:00:00.000,CA-2011-130813,High,OFF-PA-10002005,Xerox 225,9.33,3,West,36624,19,Consumer,2011-01-09 00:00:00.000,Second Class,4.37,California,Paper,2011,North America,2
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.00,US,1,2011-01-21 00:00:00.000,CA-2011-148614,Medium,OFF-PA-10002893,"Wirebound Service Call Books, 5 1/2"" x 4""",9.29,2,West,37033,19,Consumer,2011-01-26 00:00:00.000,Standard Class,0.94,California,Paper,2011,North America,4
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,1,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10000659,"Adams Phone Message Book, Professional, 400 Me...",9.84,3,West,31468,21,Consumer,2011-08-09 00:00:00.000,Standard Class,1.81,California,Paper,2011,North America,32
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.00,US,1,2011-08-05 00:00:00.000,CA-2011-118962,Medium,OFF-PA-10001144,Xerox 1913,53.26,2,West,31469,111,Consumer,2011-08-09 00:00:00.000,Standard Class,4.59,California,Paper,2011,North America,32
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.00,US,1,2011-09-29 00:00:00.000,CA-2011-146969,High,OFF-PA-10002105,Xerox 223,3.11,1,West,32440,6,Consumer,2011-10-03 00:00:00.000,Standard Class,1.32,California,Paper,2011,North America,40

Last 5 rows:

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
51285,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.20,US,1,2014-12-03 00:00:00.000,CA-2014-109701,High,OFF-BI-10000632,Satellite Sectional Post Binders,22.57,2,West,33646,69,Corporate,2014-12-04 00:00:00.000,Same Day,5.15,California,Binders,2014,North America,49
51286,Office Supplies,Los Angeles,United States,AM-103604,Alice McCarthy,0.20,US,1,2014-12-03 00:00:00.000,CA-2014-109701,High,OFF-BI-10004187,Staples,3.16,6,West,33645,9,Corporate,2014-12-04 00:00:00.000,Same Day,0.44,California,Binders,2014,North America,49
51287,Office Supplies,Los Angeles,United States,HR-147704,Hallie Redmond,0.20,US,1,2014-12-18 00:00:00.000,CA-2014-106964,Medium,OFF-BI-10000320,GBC Plastic Binding Combs,4.28,2,West,32321,12,Home Office,2014-12-21 00:00:00.000,First Class,0.31,California,Binders,2014,North America,51
51288,Office Supplies,Los Angeles,United States,RM-196754,Robert Marley,0.20,US,1,2014-12-25 00:00:00.000,CA-2014-145219,Critical,OFF-BI-10001670,Vinyl Sectional Post Binders,33.93,3,West,35917,90,Home Office,2014-12-26 00:00:00.000,First Class,15.95,California,Binders,2014,North America,52
51289,Office Supplies,Los Angeles,United States,FH-143654,Fred Hopkins,0.20,US,1,2014-12-26 00:00:00.000,CA-2014-121398,Medium,OFF-BI-10001718,GBC DocuBind P50 Personal Binding Machine,51.82,3,West,37371,154,Corporate,2014-12-30 00:00:00.000,Standard Class,9.59,California,Binders,2014,North America,52

Random sample:

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
49728,Technology,Philadelphia,United States,GM-145004,Gene McClure,0.20,US,1,2012-03-26 00:00:00.000,CA-2012-167374,Medium,TEC-AC-10004633,Verbatim 25 GB 6x Blu-ray Single Layer Recorda...,5.03,3,East,36401,17,Consumer,2012-03-30 00:00:00.000,Second Class,2.40,Pennsylvania,Accessories,2012,North America,13
45547,Office Supplies,Wollongong,Australia,NC-186251,Noah Childs,0.10,APAC,1,2011-12-15 00:00:00.000,IN-2011-67616,Medium,OFF-SU-10000954,"Acme Scissors, High Speed",37.21,7,Oceania,26147,160,Corporate,2011-12-20 00:00:00.000,Second Class,8.81,New South Wales,Supplies,2011,APAC,51
15664,Office Supplies,Galati,Romania,DK-28352,Damala Kotsonis,0.00,EMEA,1,2014-12-10 00:00:00.000,RO-2014-3800,Medium,OFF-CAR-10003030,"Cardinal Index Tab, Economy",8.04,2,EMEA,47869,18,Corporate,2014-12-14 00:00:00.000,Standard Class,1.00,Galati,Binders,2014,EMEA,50
40561,Office Supplies,Lisbon,Portugal,ZC-219102,Zuschuss Carroll,0.50,EU,1,2014-08-27 00:00:00.000,IT-2014-5630655,Medium,OFF-PA-10001971,"Eaton Memo Slips, Premium",-11.10,5,South,10640,34,Consumer,2014-09-03 00:00:00.000,Standard Class,1.30,Lisboa,Paper,2014,EU,35
49426,Furniture,Coral Springs,United States,NG-183554,Nat Gilpin,0.20,US,1,2012-09-15 00:00:00.000,US-2012-130519,High,FUR-FU-10003394,"Tenex ""The Solids"" Textured Chair Mats",-2.10,1,South,32493,56,Corporate,2012-09-15 00:00:00.000,Same Day,8.08,Florida,Furnishings,2012,North America,37

## 2. Dataset Size

This section checks the number of rows and columns in the dataset.
Each row appears to represent one order line, not one full order.
This is important because a single order can contain multiple products.

In [46]:
rows, columns = df.shape

print(f"Number of rows: {rows:,}")
print(f"Number of columns: {columns}")

Number of rows: 51,290
Number of columns: 27

Each row represents one order line, not necessarily one complete order.

For example, if a customer places one order containing three products, the same Order ID may appear three times in the dataset.

## 3. Dataset Granularity

Before analyzing the data, it is important to understand what one row represents.

In this dataset, one row represents an order line.  
This means that a single order can appear multiple times if it contains multiple products.

In [47]:
granularity_summary = pd.DataFrame({
    "Metric": [
        "Total rows",
        "Unique orders",
        "Unique customers",
        "Unique products",
        "Unique countries",
        "Unique cities"
    ],
    "Value": [
        df.shape[0],
        df["Order.ID"].nunique(),
        df["Customer.ID"].nunique(),
        df["Product.ID"].nunique(),
        df["Country"].nunique(),
        df["City"].nunique()
    ]
})

granularity_summary

             Metric  Value
0        Total rows  51290
1     Unique orders  25035
2  Unique customers   4873
3   Unique products  10292
4  Unique countries    147
5     Unique cities   3636

### Observation

The dataset contains more rows than unique orders.  
This confirms that the dataset is at the order-line level, meaning one order can contain several products.

## 4. Column Overview

This section lists all columns available in the dataset.

In [48]:
pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values,
    "Non-Null Values": df.notnull().sum().values,
    "Unique Values": df.nunique().values
})

       Column Name Data Type  Non-Null Values  Unique Values
0         Category    object            51290              3
1             City    object            51290           3636
2          Country    object            51290            147
3      Customer.ID    object            51290           4873
4    Customer.Name    object            51290            795
5         Discount   float64            51290             27
6           Market    object            51290              7
7              记录数     int64            51290              1
8       Order.Date    object            51290           1430
9         Order.ID    object            51290          25035
10  Order.Priority    object            51290              4
11      Product.ID    object            51290          10292
12    Product.Name    object            51290           3788
13          Profit   float64            51290          24575
14        Quantity     int64            51290             14
15          Region    object            51290             13
16          Row.ID     int64            51290          51290
17           Sales     int64            51290           2246
18         Segment    object            51290              3
19       Ship.Date    object            51290           1464
20       Ship.Mode    object            51290              4
21   Shipping.Cost   float64            51290          16877
22           State    object            51290           1094
23    Sub.Category    object            51290             17
24            Year     int64            51290              4
25         Market2    object            51290              6
26         weeknum     int64            51290             53

## 5. Data Types

This step checks whether each column has the appropriate data type.

For example, date columns should be converted to datetime format during the cleaning phase.

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 27 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   记录数             51290 non-null  int64
 8   Order.Date      51290 non-null  object
 9   Order.ID        51290 non-null  object
 10  Order.Priority  51290 non-null  object
 11  Product.ID      51290 non-null  object
 12  Product.Name    51290 non-null  object
 13  Profit          51290 non-null  float64
 14  Quantity        51290 non-null  int64
 15  Region          51290 non-null  object
 16  Row.ID          51290 non-null  int64
 17  Sales           51290 non-null  int64
 18  Segment         51290 non-null  object
 19  Ship.Date       51290 non-null  object
 20  Ship.Mode       51290 non-null  object
 21  Shipping.Cost   51290 non-null  float64
 22  State           51290 non-null  object
 23  Sub.Category    51290 non-null  object
 24  Year            51290 non-null  int64
 25  Market2         51290 non-null  object
 26  weeknum         51290 non-null  int64
dtypes: float64(3), int64(6), object(18)
memory usage: 10.6+ MB

### Observation

The columns `Order.Date` and `Ship.Date` are currently stored as text/object values.  
They will need to be converted into date format during the data cleaning phase.

Most numerical columns such as `Sales`, `Profit`, `Quantity`, `Discount`, and `Shipping.Cost` are already stored as numerical values.

## 6. Data Dictionary

The following table explains the business meaning of the main columns used in this project.

In [50]:
data_dictionary = pd.DataFrame({
    "Column": [
        "Order.ID",
        "Order.Date",
        "Ship.Date",
        "Ship.Mode",
        "Order.Priority",
        "Customer.ID",
        "Customer.Name",
        "Segment",
        "Country",
        "City",
        "State",
        "Region",
        "Market",
        "Product.ID",
        "Product.Name",
        "Category",
        "Sub.Category",
        "Sales",
        "Quantity",
        "Discount",
        "Profit",
        "Shipping.Cost",
        "Row.ID",
        "Year",
        "weeknum",
        "Market2",
        "记录数"
    ],
    "Description": [
        "Unique identifier of the order",
        "Date when the order was placed",
        "Date when the order was shipped",
        "Shipping method selected for the order",
        "Priority level of the order",
        "Unique identifier of the customer",
        "Customer name",
        "Customer segment: Consumer, Corporate, or Home Office",
        "Country where the order was placed",
        "City where the order was placed",
        "State or province of the order",
        "Geographical region",
        "Market where the order belongs",
        "Product identifier",
        "Product name",
        "Main product category",
        "Detailed product sub-category",
        "Revenue generated by the order line",
        "Number of units sold",
        "Discount applied to the order line",
        "Profit generated by the order line",
        "Shipping cost associated with the order line",
        "Unique identifier for each row/order line",
        "Year of the order",
        "Week number of the order",
        "Grouped market classification",
        "Record counter column; likely not useful for analysis"
    ]
})

data_dictionary

            Column                                        Description
0         Order.ID                     Unique identifier of the order
1       Order.Date                     Date when the order was placed
2        Ship.Date                    Date when the order was shipped
3        Ship.Mode             Shipping method selected for the order
4   Order.Priority                        Priority level of the order
5      Customer.ID                  Unique identifier of the customer
6    Customer.Name                                      Customer name
7          Segment  Customer segment: Consumer, Corporate, or Home...
8          Country                 Country where the order was placed
9             City                    City where the order was placed
10           State                     State or province of the order
11          Region                                Geographical region
12          Market                     Market where the order belongs
13      Product.ID                                 Product identifier
14    Product.Name                                       Product name
15        Category                              Main product category
16    Sub.Category                      Detailed product sub-category
17           Sales                Revenue generated by the order line
18        Quantity                               Number of units sold
19        Discount                 Discount applied to the order line
20          Profit                 Profit generated by the order line
21   Shipping.Cost       Shipping cost associated with the order line
22          Row.ID          Unique identifier for each row/order line
23            Year                                  Year of the order
24         weeknum                           Week number of the order
25         Market2                      Grouped market classification
26             记录数  Record counter column; likely not useful for a...

## 7. Data Quality Checks

This section checks whether the dataset contains missing values, duplicate rows, or obvious quality issues.

In [51]:
quality_checks = pd.DataFrame({
    "Check": [
        "Missing values",
        "Duplicated rows",
        "Duplicated Row.ID",
        "Negative sales",
        "Negative quantity",
        "Negative shipping cost",
        "Discount below 0",
        "Discount above 1"
    ],
    "Result": [
        df.isnull().sum().sum(),
        df.duplicated().sum(),
        df["Row.ID"].duplicated().sum(),
        (df["Sales"] < 0).sum(),
        (df["Quantity"] < 0).sum(),
        (df["Shipping.Cost"] < 0).sum(),
        (df["Discount"] < 0).sum(),
        (df["Discount"] > 1).sum()
    ]
})

quality_checks

                    Check  Result
0          Missing values       0
1         Duplicated rows       0
2       Duplicated Row.ID       0
3          Negative sales       0
4       Negative quantity       0
5  Negative shipping cost       0
6        Discount below 0       0
7        Discount above 1       0

### Observation

The dataset does not contain missing values or duplicated rows.  
No negative values were found in sales, quantity, shipping cost, or discount.

Negative profit values exist, but they are not data errors.  
They represent real business situations where some products were sold at a loss.

## 8. Date Coverage

This section checks the period covered by the dataset and verifies whether shipping dates are consistent with order dates.

In [52]:
df_dates = df.copy()

df_dates["Order.Date"] = pd.to_datetime(df_dates["Order.Date"])
df_dates["Ship.Date"] = pd.to_datetime(df_dates["Ship.Date"])

date_summary = pd.DataFrame({
    "Metric": [
        "First order date",
        "Last order date",
        "First ship date",
        "Last ship date",
        "Orders with ship date before order date"
    ],
    "Value": [
        df_dates["Order.Date"].min(),
        df_dates["Order.Date"].max(),
        df_dates["Ship.Date"].min(),
        df_dates["Ship.Date"].max(),
        (df_dates["Ship.Date"] < df_dates["Order.Date"]).sum()
    ]
})

date_summary

                                    Metric                Value
0                         First order date  2011-01-01 00:00:00
1                          Last order date  2014-12-31 00:00:00
2                          First ship date  2011-01-03 00:00:00
3                           Last ship date  2015-01-07 00:00:00
4  Orders with ship date before order date                    0

In [53]:
df_dates["Shipping.Delay"] = (df_dates["Ship.Date"] - df_dates["Order.Date"]).dt.days

df_dates["Shipping.Delay"].describe()

count   51,290.00
mean         3.97
std          1.73
min          0.00
25%          3.00
50%          4.00
75%          5.00
max          7.00
Name: Shipping.Delay, dtype: float64

### Observation

The dataset covers orders from 2011 to 2014.  
Shipping dates may slightly extend beyond the last order date because some orders are shipped after being placed.

## 9. Numerical Summary

This section gives an overview of the main numerical variables used in the analysis.

In [54]:
numeric_columns = ["Sales", "Profit", "Quantity", "Discount", "Shipping.Cost"]

df[numeric_columns].describe().T.round(2)

                  count   mean    std       min   25%   50%    75%       max
Sales         51,290.00 246.50 487.57      0.00 31.00 85.00 251.00 22,638.00
Profit        51,290.00  28.61 174.34 -6,599.98  0.00  9.24  36.81  8,399.98
Quantity      51,290.00   3.48   2.28      1.00  2.00  3.00   5.00     14.00
Discount      51,290.00   0.14   0.21      0.00  0.00  0.00   0.20      0.85
Shipping.Cost 51,290.00  26.38  57.30      0.00  2.61  7.79  24.45    933.57

In [55]:
profit_summary = pd.DataFrame({
    "Metric": [
        "Total sales",
        "Total profit",
        "Average profit per row",
        "Number of loss-making rows",
        "Number of profitable rows",
        "Number of zero-profit rows"
    ],
    "Value": [
        df["Sales"].sum(),
        df["Profit"].sum(),
        df["Profit"].mean(),
        (df["Profit"] < 0).sum(),
        (df["Profit"] > 0).sum(),
        (df["Profit"] == 0).sum()
    ]
})

profit_summary

                       Metric         Value
0                 Total sales 12,642,905.00
1                Total profit  1,467,457.29
2      Average profit per row         28.61
3  Number of loss-making rows     12,544.00
4   Number of profitable rows     38,078.00
5  Number of zero-profit rows        668.00

### Observation

The dataset contains both profitable and loss-making transactions.  
This makes it highly relevant for a profitability analysis because it allows us to investigate which products, customers, regions, or discount levels reduce overall profit.

## 10. Categorical Summary

This section summarizes the main categorical variables, such as categories, segments, markets, and shipping modes.

In [56]:
categorical_columns = df.select_dtypes(include="object").columns

categorical_summary = pd.DataFrame({
    "Column": categorical_columns,
    "Unique Values": [df[col].nunique() for col in categorical_columns],
    "Most Frequent Value": [df[col].mode()[0] for col in categorical_columns],
    "Frequency": [df[col].value_counts().iloc[0] for col in categorical_columns]
})

categorical_summary

            Column  Unique Values      Most Frequent Value  Frequency
0         Category              3          Office Supplies      31273
1             City           3636            New York City        915
2          Country            147            United States       9994
3      Customer.ID           4873                JG-158051         40
4    Customer.Name            795          Muhammed Yedwab        108
5           Market              7                     APAC      11002
6       Order.Date           1430  2014-06-18 00:00:00.000        135
7         Order.ID          25035           CA-2014-100111         14
8   Order.Priority              4                   Medium      29433
9       Product.ID          10292          OFF-AR-10003651         35
10    Product.Name           3788                  Staples        227
11          Region             13                  Central      11117
12         Segment              3                 Consumer      26518
13       Ship.Date           1464  2014-11-22 00:00:00.000        130
14       Ship.Mode              4           Standard Class      30775
15           State           1094               California       2001
16    Sub.Category             17                  Binders       6152
17         Market2              6                     APAC      11002

In [57]:
categorical_columns_to_display = ["Category", "Segment", "Market", "Ship.Mode"]

for col in categorical_columns_to_display:
    print(f"\n\n Value counts for {col}:")
    display(df[col].value_counts().to_frame("Count"))

 Value counts for Category:

                 Count
Category
Office Supplies  31273
Technology       10141
Furniture         9876

 Value counts for Segment:

             Count
Segment
Consumer     26518
Corporate    15429
Home Office   9343

 Value counts for Market:

        Count
Market
APAC    11002
LATAM   10294
EU      10000
US       9994
EMEA     5029
Africa   4587
Canada    384

 Value counts for Ship.Mode:

                Count
Ship.Mode
Standard Class  30775
Second Class    10309
First Class      7505
Same Day         2701

## 11. Potential Data Issues Identified

During the data understanding phase, a few points were identified for the cleaning phase:

1. The columns `Order.Date` and `Ship.Date` should be converted to datetime format.
2. The column `记录数` appears to be a record counter and does not provide analytical value.
3. Column names contain dots and inconsistent naming conventions, which should be cleaned.
4. A small number of rows have sales equal to zero and should be reviewed.
5. `Order.ID` is not unique because one order can contain multiple products.
6. `Row.ID` appears to be the unique identifier for each row.

In [58]:
zero_sales_count = (df["Sales"] == 0).sum()

print(f"Number of rows with zero sales: {zero_sales_count}")

if zero_sales_count > 0:
    display(df[df["Sales"] == 0])

Number of rows with zero sales: 1

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,记录数,Order.Date,Order.ID,Order.Priority,Product.ID,Product.Name,Profit,Quantity,Region,Row.ID,Sales,Segment,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum
46158,Office Supplies,Houston,United States,ZC-219104,Zuschuss Carroll,0.80,US,1,2014-06-20 00:00:00.000,US-2014-102288,Medium,OFF-AP-10002906,Hoover Replacement Belt for Commercial Guardsm...,-1.11,1,Central,35398,0,Consumer,2014-06-24 00:00:00.000,Standard Class,0.01,Texas,Appliances,2014,North America,25

### Observation


Rows with zero sales should be reviewed if they exist.  
They should not be removed automatically without understanding whether they represent valid records, rounding issues, or data entry problems.

## 12. Final Data Understanding Summary

The table below summarizes the main findings from the data understanding phase.

In [59]:
final_data_understanding_summary = pd.DataFrame({
    "Area": [
        "Dataset size",
        "Granularity",
        "Missing values",
        "Duplicate rows",
        "Date columns",
        "Profit values",
        "Technical columns",
        "Overall status"
    ],
    "Finding": [
        "51,290 rows and 27 columns",
        "One row represents one order line",
        "No missing values detected",
        "No duplicated rows detected",
        "Order.Date and Ship.Date need conversion",
        "Negative profits exist and represent loss-making transactions",
        "Some columns need review or removal",
        "Dataset is suitable for analysis after cleaning"
    ]
})

final_data_understanding_summary

                Area                                            Finding
0       Dataset size                         51,290 rows and 27 columns
1        Granularity                  One row represents one order line
2     Missing values                         No missing values detected
3     Duplicate rows                        No duplicated rows detected
4       Date columns           Order.Date and Ship.Date need conversion
5      Profit values  Negative profits exist and represent loss-maki...
6  Technical columns                Some columns need review or removal
7     Overall status    Dataset is suitable for analysis after cleaning

## 13. Final Decision

Based on the data understanding phase, the Global Superstore dataset is suitable for the Profitability Optimization project.

The dataset contains enough information to analyze sales performance, profitability, discounts, customers, products, regions, and shipping costs.

However, the dataset should be cleaned and prepared before moving to exploratory analysis, SQL analysis, Excel, or Power BI.

## 14. Conclusion

The Global Superstore dataset is suitable for the Profitability Optimization project.

It contains more than 50,000 order lines across multiple countries, markets, product categories, customer segments, and shipping methods.

The dataset has no missing values and no duplicated rows, which makes it reliable for further analysis. However, several preparation steps are required before moving forward:

- Convert `Order.Date` and `Ship.Date` to datetime format.
- Rename columns for better readability and consistency.
- Remove or ignore non-useful technical columns such as `记录数`.
- Create new business variables such as `profit_margin`, `shipping_delay`, `month`, and `quarter`.
- Review zero-sales records instead of deleting them automatically.
- Prepare a clean dataset that can be reused in Python, SQL, Excel, and Power BI.

The next step will be the Data Cleaning and Preparation phase.